### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Bartolomeus-649** [microsoft/AMBROSIA#115]
So is Ambrosia another dead and abandoned project by Microsoft?

**Comment by jongoldDB** [comment]
Hi all,

I just want to let you know that Ambrosia is NOT dead. We are currently working on a number of very significant improvements, including scaleout, and support for other languages. Stay tuned :)

**Comment by miroslavp** [comment]
Requiring Azure subscription will slow down the adoption of the technology. I understand that MS wants everyone of us to deploy on Azure, however even if I wanted there’s no Azure datacenter near where I live and the last time I checked the latency to the nearest one was horrible. Please provide alternative to Azure, otherwise it looks like a lock-in trap

**Comment by jongoldDB** [comment]
Hi @miroslavp :) In the fullness of time, we will open up the substitutability of Azure table with any persistent key value store. This being an MSR project, our resources are small, and contributions are welcome :) CRA already allows this, which is one source of Azure table usage. So someone needs to plumb this capability into Ambrosia. The other is for a bit of information like the latest log #. The logs and checkpoint are already storable anywhere in the filesystem, so there is no Azure dependency there.

**Comment by MedAnd** [comment]
Hi @jongoldDB... great to hear this work is still ongoing! Have just asked over at the Durable Functions project if there are any plans to incorporate Ambrosia with the Azure Functions project? Could be wrong but feels like an excellent fit?

cc @sebastianburckhardt

**Comment by jongoldDB** [comment]
Lots more goodies are coming this summer. Stay tuned :)
